# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(50, 40, 361, 511))
        self.frame.setStyleSheet("#frame{\n"
"background-color:qlineargradient(spread:pad, x1:0.711, y1:0.693182, x2:1, y2:0, stop:0 rgba(153, 34, 57, 254), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius:20px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(60, 70, 241, 51))
        self.label.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 87 16pt \"Arial Black\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 130, 341, 41))
        self.label_2.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 87 16pt \"Arial Black\";")
        self.label_2.setObjectName("label_2")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(410, 70, 311, 451))
        self.frame_2.setStyleSheet("#frame_2{\n"
"    background-color:rgb(255, 255, 255);\n"
"    border-top-right-radius:20px;\n"
"    border-bottom-right-radius:20px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(250, 10, 51, 28))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton::hover{\n"
"    padding-bottom:5px\n"
"}\n"
"")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/关闭.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(30, 30))
        self.pushButton.setObjectName("pushButton")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(-1, 39, 311, 401))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame_6)
        self.stackedWidget_2.setStyleSheet("QLineEdit{\n"
"\n"
"    background-color: rgba(255, 255, 255,0);\n"
"    border:none;\n"
"    border-bottom:1px solid black;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:7px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_Login = QtWidgets.QWidget()
        self.page_Login.setObjectName("page_Login")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_Login)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lineEdit_R_Account = QtWidgets.QLineEdit(self.page_Login)
        self.lineEdit_R_Account.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_R_Account.setObjectName("lineEdit_R_Account")
        self.verticalLayout_6.addWidget(self.lineEdit_R_Account)
        self.lineEdit_R_Password1 = QtWidgets.QLineEdit(self.page_Login)
        self.lineEdit_R_Password1.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_R_Password1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_R_Password1.setObjectName("lineEdit_R_Password1")
        self.verticalLayout_6.addWidget(self.lineEdit_R_Password1)
        self.lineEdit_R_Password2 = QtWidgets.QLineEdit(self.page_Login)
        self.lineEdit_R_Password2.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_R_Password2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_R_Password2.setObjectName("lineEdit_R_Password2")
        self.verticalLayout_6.addWidget(self.lineEdit_R_Password2)
        self.pushButton_R_Sure = QtWidgets.QPushButton(self.page_Login)
        self.pushButton_R_Sure.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_R_Sure.setObjectName("pushButton_R_Sure")
        self.verticalLayout_6.addWidget(self.pushButton_R_Sure)
        self.stackedWidget_2.addWidget(self.page_Login)
        self.page_register = QtWidgets.QWidget()
        self.page_register.setObjectName("page_register")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_register)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lineEdit_L_Account = QtWidgets.QLineEdit(self.page_register)
        self.lineEdit_L_Account.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_L_Account.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_L_Account.setObjectName("lineEdit_L_Account")
        self.verticalLayout_5.addWidget(self.lineEdit_L_Account)
        self.lineEdit_L_Password = QtWidgets.QLineEdit(self.page_register)
        self.lineEdit_L_Password.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_L_Password.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_L_Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_L_Password.setObjectName("lineEdit_L_Password")
        self.verticalLayout_5.addWidget(self.lineEdit_L_Password)
        self.pushButton_L_Sure = QtWidgets.QPushButton(self.page_register)
        self.pushButton_L_Sure.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_L_Sure.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_L_Sure.setObjectName("pushButton_L_Sure")
        self.verticalLayout_5.addWidget(self.pushButton_L_Sure)
        self.stackedWidget_2.addWidget(self.page_register)
        self.verticalLayout_4.addWidget(self.stackedWidget_2)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Login = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_Login.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/登录.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Login.setIcon(icon1)
        self.pushButton_Login.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_Login.setObjectName("pushButton_Login")
        self.horizontalLayout.addWidget(self.pushButton_Login)
        self.pushButton_Register = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_Register.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/注册.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Register.setIcon(icon2)
        self.pushButton_Register.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_Register.setObjectName("pushButton_Register")
        self.horizontalLayout.addWidget(self.pushButton_Register)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_2.raise_()
        self.frame.raise_()
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        self.stackedWidget_2.setCurrentIndex(1)
        self.stackedWidget.setCurrentIndex(0)
        self.pushButton.clicked.connect(LoginWindow.close)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "MainWindow"))
        self.label.setText(_translate("LoginWindow", "Welcome to the "))
        self.label_2.setText(_translate("LoginWindow", "fall recognition system"))
        self.lineEdit_R_Account.setPlaceholderText(_translate("LoginWindow", "账号："))
        self.lineEdit_R_Password1.setPlaceholderText(_translate("LoginWindow", "密码："))
        self.lineEdit_R_Password2.setPlaceholderText(_translate("LoginWindow", "确认密码："))
        self.pushButton_R_Sure.setText(_translate("LoginWindow", "注册"))
        self.lineEdit_L_Account.setPlaceholderText(_translate("LoginWindow", "账号："))
        self.lineEdit_L_Password.setPlaceholderText(_translate("LoginWindow", "密码："))
        self.pushButton_L_Sure.setText(_translate("LoginWindow", "确认"))
import res_rc
